### ISSUE TITLE
Coveralls should be a dev dependency

### ISSUE THREAD

**Issue by renchap** [y-yagi/minitest-test_profile#8]
At the moment coveralls is a normal dependency, causing a few additional deps (netrc, rest-client, simplecov, ...) to be installed when you add `minitest-test_profile` to your gemfile. I think it should be moved to a development dependency, as it is only used when running the test suite.

**Comment by y-yagi** [comment]
Thanks for your report! Your point is really correct. 
I fixed this and released the new version. Thanks!
